### ISSUE TITLE
Customize font size

### ISSUE THREAD

**Issue by matinnuhamunada** [mwouts/itables#104]
Hi, thanks for developing this awesome tool :)

I tried to go through the documentation but am unable to find clues on how to customize font sizes.
Is that something that can be done via `itables.options`?

**Comment by mwouts** [comment]
Hi @matinnuhamunada , sorry for not being able to answer before.

According to [this thread](https://datatables.net/forums/discussion/66743/change-text-size-in-datatable) you will have to change the CSS for this.

This is not something that is currently possible in `itables`.

Still, if you have a minute to make an experiment, I would suggest that you try to modify the content of [`itables/html/style.css`](https://github.com/mwouts/itables/blob/main/itables/html/style.css) that you use locally, and let us know how it goes? If that turns out to work then I'd be happy to add the option to use custom CSS files.

**Comment by mwouts** [comment]
Hi @matinnuhamunada , well actually it is super easy to move the CSS to `itables.options`, so I have prepared a new version in the PR above.

However I am not 100% sure it works as expected... At least when I compile the documentation, the font size that I intended to change just for one table actually changed for all the tables on the page...
![image](https://user-images.githubusercontent.com/29915202/199356887-252a1d5b-fad4-4073-b0d7-b6d04014c284.png)

Maybe someone with more knowledge of CSS than myself could help... To install the development version that has the new `css` option both in `itables.options` and `show`, you'll just need to run this:
```
pip install git+https://github.com/mwouts/itables.git@custom_css
```

**Comment by mwouts** [comment]
I have released a new version that has the `css` argument in `show` (Version 1.3.1). The CSS should be the same for all the tables in a given notebook so you probably want to change `opt.css` directly. By the way, please let me know if you see changes that we should make on the default CSS!
