### ISSUE TITLE
ITables 2.0.0rc0 fails to work in Quarto

### ISSUE THREAD

**Issue by mwouts** [mwouts/itables#238]
- In the offline mode (the default), the error is `Uncaught TypeError: $t.default.ext is undefined`
- In the connected mode, the error is the same as for VS Code (#237 )

**Comment by mwouts** [comment]
The problem disappeared when I removed `datatables.net-colreorder-dt` from the bundle: https://github.com/mwouts/itables/pull/235/commits/0e64e98e7f825402e2f2aea0121e03205ccd3811. 

That's also the difference between [dt_for_itables](https://www.npmjs.com/package/dt_for_itables/) between v2.0.0 (which fails with the error above) and v2.0.1 (which works).

@AllanJard do you expect an incompatibility between the `colreorder` extension and the other ones? (really not an issue for me, just FYI)

**Comment by AllanJard** [comment]
I haven't encountered one before with the current releases. The [examples on my site](https://datatables.net/extensions/colreorder/examples/initialisation/simple.html) work okay, although they are direct inclusion of the script files rather than npm modules.

I've just tried it with the npm modules [here](https://stackblitz.com/edit/vitejs-vite-7etxqn?file=index.html%2Csrc%2Fmain.ts%2Csrc%2Fstyle.css&terminal=dev) and it appears to work okay as well.

**Comment by mwouts** [comment]
Oh sorry I could have made a clearer comment. With the first version of the bundle, all the extensions including colreorder were working in both Jupyter Lab and Jupyter Book. But in both Jupyter in VS Code and Quarto I could not display a DataTable. So I tried to remove progressively the extensions and it turned out that I could get DataTable to work in all the context I wanted by just removing the colreorder extension from the bundle. I am very happy with the result, and I think I am going to use a lot the searchPanes, searchBuilder and Buttons extensions!
