### ISSUE TITLE
Long column names overlay

### ISSUE THREAD

**Issue by yotammarton** [mwouts/itables#28]
![image](https://user-images.githubusercontent.com/43007010/134821375-f700cb37-b178-425e-aba9-085f8c91cfd6.png)

Columns names should either show "aaa..." with option to hover or either be in the minimum width of the column name.

Thanks for this package :)

**Comment by Lance628** [comment]
Any update? I am also facing this problem

**Comment by mwouts** [comment]
Hi, sorry it took me a long time to address this issue. Anyway, it turned to be an easy one: I just had to change the style for `table th`, see the PR above.

This is fixed in `itables==0.4.1`, cf [this notebook](https://github.com/mwouts/itables/blob/main/tests/test_long_column_names.md) that you can try directly on [binder](https://mybinder.org/v2/gh/mwouts/itables/main?urlpath=lab/tree/tests/test_long_column_names.md):
![image](https://user-images.githubusercontent.com/29915202/148463362-49d96f72-799f-442d-ad3d-4c1038e35d63.png)
