### ISSUE TITLE
UnicodeDecodeError while set "connected=False"

### ISSUE THREAD

**Issue by Samox1** [mwouts/itables#285]
I encountered a problem the first time I ran in jupyter notebook - the file contains only:
```python
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True, connected=False)
```

Error:

```bash
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[3], [line 2](vscode-notebook-cell:?execution_count=3&line=2)
      [1] from itables import init_notebook_mode
----> [2] init_notebook_mode(all_interactive=True, connected=False)


[...]

File ~\AppData\Local\Programs\Python\Python310\lib\encodings\cp1250.py:23, in IncrementalDecoder.decode(self, input, final)
     [22] def decode(self, input, final=False):
---> [23]     return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 194869: character maps to <undefined>
```

When set "connected=True" everything works properly.

itables version 2.1.0

**Comment by mwouts** [comment]
Hi @Samox1 , thank you for reporting this! This problem was initially reported at #252 and I have a PR ready to be tested in #253, but I could never reproduce the issue myself so I'd like to get confirmation that it does solve the issue before merging.

Do you think you could try the instruction [here](https://github.com/mwouts/itables/pull/253#issuecomment-2028059053) to test the PR? You will have to install `nodejs`. If that does not work for you let me know and I will publish a release candidate.

**Comment by mwouts** [comment]
Actually I have just released `itables=2.1.1` with the fix. Let me know how it goes.

**Comment by Samox1** [comment]
Oh sorry, I looked for this problem in Issues but couldn't find it, that's why I described the problem.

I will check this issue in the near future and let you know.

**Comment by mwouts** [comment]
No problem at all! Thanks for reporting the issue. Sure, keep me posted!

**Comment by Samox1** [comment]
Tested on new venv - ```init_notebook_mode(all_interactive=True, connected=False)``` works without issue - really love this simple view!

Tested on: Windows 10 / Python 3.10.7 / ipynb in VS Code
