### ISSUE TITLE
Publish itables on conda

### ISSUE THREAD

**Issue by fwouts** [mwouts/itables#96]
I'd like to use itables but I use Anaconda to manage Python packages. It would be a big help if I could use it there!

**Comment by mwouts** [comment]
Hi @fwouts , I just opened a [PR](https://github.com/conda-forge/staged-recipes/pull/20303) to publish `itables` on `conda-forge`, but... it's already there!

The repo where the recipe is maintained is https://github.com/conda-forge/itables-feedstock, and it has been maintained by @asford since Jan 2022 (thank you Alex!)

This means that you can get `itables` by simply typing
```
conda install itables -c conda-forge
```
or even
```
conda install itables
```
provided that you have something like this in your `~/.condarc`:
```
channels:
  - defaults
  - conda-forge
```
